<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>FFXIVOptiScalerCompanion</AssemblyName>
    <Version>0.1.2</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <RestoreConfigFile>$(MSBuildThisFileDirectory)..\NuGet.Config</RestoreConfigFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Dalamud"><HintPath>$(DalamudLibPath)\Dalamud.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Dalamud.Bindings.ImGui"><HintPath>$(DalamudLibPath)\Dalamud.Bindings.ImGui.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="FFXIVClientStructs"><HintPath>$(DalamudLibPath)\FFXIVClientStructs.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="InteropGenerator.Runtime"><HintPath>$(DalamudLibPath)\InteropGenerator.Runtime.dll</HintPath><Private>false</Private></Reference>
    <None Update="FFXIVOptiScalerCompanion.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
